# 
# (C) Copyright 2015 Oleg Rakhmanov <oleg@archlinuxarm.org>
#
# Based on
# (C) Copyright 2015 bodhi <mibodhi@gmail.com>
#
# Prafulla Wadaskar <prafulla@marvell.com>
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= nsa325.o
