# 
# (C) Copyright 2015 Oleg Rakhmanov <oleg@archlinuxarm.org>
#
# Based on
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= pogoplugv4.o
